import Link from "next/link";

export default function Footer() {
  return (
    <footer className="mt-24 border-t border-line pt-8 pb-4">
      <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
        <span className="text-xs font-semibold tracking-widest uppercase text-brass-deep">
          Knollside
        </span>
        <div className="flex flex-wrap items-center gap-x-6 gap-y-2 text-sm text-[#8A836F]">
          <Link href="/terms" className="hover:text-[#211F1B]">
            Terms of Service
          </Link>
          <Link href="/privacy" className="hover:text-[#211F1B]">
            Privacy Policy
          </Link>
          <a
            href="mailto:hello@knollside.com"
            className="font-mono text-xs hover:text-[#211F1B]"
          >
            hello@knollside.com
          </a>
        </div>
      </div>
      <p className="mt-6 text-xs text-[#8A836F]">
        &copy; {new Date().getFullYear()} Knollside. Quotes generated by the
        widget are estimates set by each business, not offers from Knollside.
      </p>
    </footer>
  );
}
